# Generated by Django 4.1.3 on 2023-06-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_name", models.IntegerField()),
                ("name_ko", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=25)),
                ("dir", models.CharField(max_length=20)),
                ("part", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "exercises",
                "managed": False,
            },
        ),
    ]
