# Generated by Django 4.1.3 on 2023-08-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercises",
            fields=[
                ("id_name", models.IntegerField(primary_key=True, serialize=False)),
                ("name_ko", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=25)),
                ("dir", models.CharField(max_length=20)),
                ("part", models.CharField(max_length=50)),
            ],
        ),
    ]
